### ISSUE TITLE
Improved code

### ISSUE THREAD

**Issue by porfanid** [f-mohamed-abdullah/Student-CRUD#4]
I added an separate class to use for the database connection. In this way, if you want to add more users to the future, you will not create multiple database connections.

Also, I would recommend that you put the credentials to the database on a .env file so that they remain safe and you don't accidentally push them to the GitHub

**Comment by f-mohamed-abdullah** [comment]
Yeah @porfanid merged your work bro 🫡 !!!

**Comment by f-mohamed-abdullah** [comment]
> I added an separate class to use for the database connection. In this way, if you want to add more users to the future, you will not create multiple database connections.
> 
> Also, I would recommend that you put the credentials to the database on a .env file so that they remain safe and you don't accidentally push them to the GitHub

Nice work @porfanid i just merged your code 👨‍💻,If you like this project then star ⭐️ this repo and do more contributions.

**Comment by porfanid** [comment]
> > I added an separate class to use for the database connection. In this way, if you want to add more users to the future, you will not create multiple database connections.
> > Also, I would recommend that you put the credentials to the database on a .env file so that they remain safe and you don't accidentally push them to the GitHub
> 
> Nice work @porfanid i just merged your code 👨‍💻,If you like this project then star ⭐️ this repo and do more contributions.

Will do. Thank you
